kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hamm-api-server-roles
subjects:
- kind: ServiceAccount
  name: hamm-api-server-sa
roleRef:
  kind: Role
  name: use-pod-security-policy-role
  apiGroup: rbac.authorization.k8s.io
